
services:
  mysql:
    image: mysql:8.0
    container_name: game-manager-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bootdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - inatel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  game-manager:
    build: .
    container_name: game-manager
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inatel
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bootdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  publisher-manager:
    image: adautomendes/publisher-manager:latest
    container_name: publisher-manager
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inatel
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      SPRING_PROFILES_ACTIVE: prod

volumes:
  mysql_data:

networks:
  inatel:
    driver: bridge
