
services:
  mysql:
    image: mysql:8.0
    container_name: game-manager-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - inatel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  game-manager:
    build: .
    container_name: game-manager
    ports:
      - "${GAME_MANAGER_PORT}:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inatel
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      PUBLISHER_MANAGER_URL: ${PUBLISHER_MANAGER_URL}

  publisher-manager:
    image: adautomendes/publisher-manager:${PUBLISHER_MANAGER_VERSION}
    container_name: publisher-manager
    platform: linux/amd64
    ports:
      - "${PUBLISHER_MANAGER_PORT}:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inatel
    environment:
      SERVER_HOST: ${PUBLISHER_SERVER_HOST}
      SERVER_PORT: ${PUBLISHER_SERVER_PORT}
      MYSQL_HOST: ${PUBLISHER_MYSQL_HOST}
      MYSQL_PORT: ${PUBLISHER_MYSQL_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

volumes:
  mysql_data:

networks:
  inatel:
    driver: bridge
